export CMAKE_ARGS="${CMAKE_ARGS} -D BUILD_DOC:BOOL=OFF -D VERSION_STRING:STRING=${PKG_VERSION}"

# if [[ "$CC_FOR_BUILD" != "" && "$CC_FOR_BUILD" != "$CC" ]]; then
#   CMAKE_ARGS="${CMAKE_ARGS} -DCMAKE_C_COMPILER=$CC_FOR_BUILD -DCMAKE_CXX_COMPILER=$CXX_FOR_BUILD"
# fi
# echo "CMAKE_ARGS: ${CMAKE_ARGS}"

${PYTHON} -m pip install . -vv