export CMAKE_ARGS="${CMAKE_ARGS} -D BUILD_DOC:BOOL=OFF -D VERSION_STRING:STRING=${PKG_VERSION} -D CMAKE_CXX_COMPILER=\$BUILD_PREFIX/bin/${CXX} -D CMAKE_C_COMPILER=\$BUILD_PREFIX/bin/${CC}"

echo "CMAKE_ARGS: ${CMAKE_ARGS}"

${PYTHON} -m pip install . -vv