{% set name = "opencamlib" %}
{% set version = "2022.12.18" %}
{% set sha256 = "24698fb937c66905f53c99d399e60623b9555f6d04a0fb3609b248a7c31c9c63" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/aewallin/{{ name }}/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 8
    skip: true  # [py<36]

requirements:
    build:
        - {{ compiler("cxx") }}
        - ninja
        - cmake
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
    host:
        - python
        - boost
    run:
        - boost
        - python

test:
  imports:
    - opencamlib
  source_files:
    - examples/python/test.py
    - stl/**
about:
    home: http://www.anderswallin.net/CAM/
    license: LGPL-2.1
    license_family: LGPL
    license_file: COPYING
    summary: OpenCAMLib (ocl)
    description: OpenCAMLib (ocl) is a c++ library for creating toolpaths for cnc-machines
                 such as mills and lathes.
    doc_url: http://www.anderswallin.net/CAM/
    dev_url: https://github.com/aewallin/opencamlib

extra:
  recipe-maintainers:
    - looooo
    - vespakoen