{% set name = "opencamlib" %}
{% set version = "2022.12.20" %}
{% set sha256 = "b598454c4aa8b20f2af19bdcac4b7e8bd245ab83ad31576e16c86edee255b482" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/vespakoen/{{ name }}/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    skip: true  # [py<36]
    script: "{{ PYTHON }} -m pip install . -vv --config-settings='cmake.args=-D BUILD_DOC:BOOL=OFF -DVERSION_STRING={{ PKG_VERSION }}'"

requirements:
    build:
        - {{ compiler("cxx") }}
        - ninja
        - cmake
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
    host:
        - python
        - pip
        - scikit-build-core
        - boost
    run:
        - boost
        - python

test:
  imports:
    - opencamlib
  source_files:
    - examples/python/test.py
    - stl/**
about:
    home: http://www.anderswallin.net/CAM/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: COPYING
    summary: OpenCAMLib (ocl)
    description: OpenCAMLib (ocl) is a c++ library for creating toolpaths for cnc-machines
                 such as mills and lathes.
    doc_url: http://www.anderswallin.net/CAM/
    dev_url: https://github.com/aewallin/opencamlib

extra:
  recipe-maintainers:
    - looooo
    - vespakoen
