{% set name = "opencamlib" %}
{% set version = "2022.12.18" %}
{% set sha256 = "24698fb937c66905f53c99d399e60623b9555f6d04a0fb3609b248a7c31c9c63" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    # url: https://github.com/aewallin/{{ name }}/archive/{{ version }}.tar.gz
    # sha256: {{ sha256 }}
    url: https://github.com/vespakoen/opencamlib/archive/refs/tags/2023.01.09.tar.gz
    sha256: 25222a83f17d8c0e2745a3e3d83866cc504119e2338e8d16b5a742e4dd1cc0cd

build:
    number: 0
    skip: true  # [py<36]

requirements:
    build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - ninja
        - cmake
        - make
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
    host:
        - python
        - pip
        - scikit-build-core
        - boost
    run:
        - boost
        - python

test:
  imports:
    - opencamlib
  source_files:
    - examples/python/test.py
    - stl/**
about:
    home: http://www.anderswallin.net/CAM/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: COPYING
    summary: OpenCAMLib (ocl)
    description: OpenCAMLib (ocl) is a C++ library for creating toolpaths for CNC-machines
                 such as mills and lathes.
    doc_url: http://www.anderswallin.net/CAM/
    dev_url: https://github.com/aewallin/opencamlib

extra:
  recipe-maintainers:
    - looooo
    - vespakoen
